#--------------------------------------------------------------#
# /$$       /$$           /$$      /$$$$$$$$/$$$$$$   /$$$$$$  #
#| $$      |__/          | $$     |_____ $$/$$$_  $$ /$$__  $$ #
#| $$$$$$$  /$$ /$$$$$$$ | $$   /$$    /$$/ $$$$\ $$|__/  \ $$ #
#| $$__  $$| $$| $$__  $$| $$  /$$/   /$$/| $$ $$ $$  /$$$$$$/ #
#| $$  \ $$| $$| $$  \ $$| $$$$$$/   /$$/ | $$\ $$$$ /$$____/  #
#| $$  | $$| $$| $$  | $$| $$_  $$  /$$/  | $$ \ $$$| $$       #
#| $$$$$$$/| $$| $$  | $$| $$ \  $$/$$/   |  $$$$$$/| $$$$$$$$ #
#|_______/ |__/|__/  |__/|__/  \__/__/     \______/ |________/ #
#--------------------------------------------------------------#

#------------------------ INDONESIA -------------------------#
# JANGAN MERUBAH AUTHOR, KALO MAU PAKE NAMA SENDIRI YA BIKIN #
# KALO GA BISA BIKIN YA BELAJAR, MAAF KALO BANYAK KEKURANGAN #
# DISCORD : hamdani#6477                                     #
# xbox    : bink702                                          #
#------------------------------------------------------------#

# Edit Dari Sini

Title: "Shop"

ShopName: "EpicShop (Money: {money})"